export const country = {
  READ: 'COUNTRY_READ',
  READ_SUCCESS: 'COUNTRY_READ_SUCCESS',
  READ_FAILURE: 'COUNTRY_READ_FAILURE',
};

export const loader = {
  ADD_ACTION: 'LOADER_ADD_ACTION',
  REMOVE_ACTION: 'LOADER_REMOVE_ACTION',
};
